spring.application.name=backend
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/ti_db
spring.datasource.username=root
spring.datasource.password=juniorjain11

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true