# Set the maximum allowed size of the client request body.
client_max_body_size 200M;

# Increase the timeout for reading the client request body.
client_body_timeout 300s;

# Increase the timeout for the proxy to wait for a response from the application.
proxy_read_timeout 300s;

# Pass essential client information to your application.
proxy_set_header   Host                 $host;
proxy_set_header   X-Real-IP            $remote_addr;
proxy_set_header   X-Forwarded-For      $proxy_add_x_forwarded_for;
proxy_set_header   X-Forwarded-Proto    $scheme;